name: Run gcloud commands

on:
  push:
    branches:
      - main

jobs:
  run_commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          project_id: carbide-oarlock-356612
          export_default_credentials: true

      - name: Run gcloud commands
        run: |
          # Example: List GCP buckets and echo some data
          gcloud auth list
          gcloud config list
          echo "Hello, GitHub Actions!"

        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
