name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.IAM }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'

      - name: Build and Package with Maven
        working-directory: ./code/api/lifeguardian
        run: |
          mvn clean package
          echo "::set-output name=war_file::$(ls target/*.war)"
      
      - name: Debugging
        run: |
          echo "Environment Variables:"
          env
          
          echo "GCloud Authentication List:"
          gcloud auth list
          
          echo "GCloud Information:"
          gcloud info
          
          echo "GCloud SCP Help:"
          gcloud compute scp --help
        shell: bash

      - name: Copy War File to Deployments Folder
        run: |
          echo "${{ secrets.GCP_VM_SSH_PRIVATE_KEY }}" > /tmp/gcp_vm_ssh_private_key
          echo "${{ secrets.GCP_VM_SSH_PUBLIC_KEY }}" > /tmp/gcp_vm_ssh_private_key.pub  # Ensure you have this secret set up
          chmod 600 /tmp/gcp_vm_ssh_private_key
          chmod 644 /tmp/gcp_vm_ssh_private_key.pub
          
          # Replace with your actual GCP VM username
          gcloud compute scp ./code/api/lifeguardian/target/*.war soulaimeneturki@cotproject/opt/wildfly/standalone/deployments --zone=us-west4-b --project=carbide-oarlock-356612 --ssh-key-file=/tmp/gcp_vm_ssh_private_key --quiet          
          
