name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Package with Maven
        working-directory: ./code/api/lifeguardian
        run: |
          mvn clean package
          echo "::set-output name=war_file::$(ls target/*.war)"

  deploy:
    runs-on: ubuntu-latest

    needs: build
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/22423504579/locations/global/workloadIdentityPools/githubactions/providers/github'
          service_account: 'github-actions@carbide-oarlock-356612.iam.gserviceaccount.com'
          
      - name: Get GCP VM Zone
        id: get_zone
        run: |
          INSTANCE_ZONE=$(gcloud compute instances describe cotproject --format='value(zone)')
          echo "::set-output name=instance_zone::$INSTANCE_ZONE"
          
      - name: SSH into GCP VM and restart WildFly
        uses: google-github-actions/setup-gcloud@v2

      - name: Copy WAR file to GCP VM
        run: |
          gcloud compute scp --zone=$INSTANCE_ZONE ${{ needs.build.outputs.war_file }} cotproject:./opt/wildfly/standalone/deployments/



