name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Package with Maven
        working-directory: ./code/api/lifeguardian
        run: |
          mvn clean package
          echo "::set-output name=war_file::$(ls target/*.war)"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Write private key to file
        run: echo "${{ secrets.GCP_PRIVATE_KEY }}" > private-key.pem
        shell: bash

      - name: Debug Secrets
        run: |
          cat private-key.pem
          ls -l private-key.pem
          echo "VM_USERNAME: ${{ secrets.VM_USERNAME }}"
        env:
          PRIVATE_KEY_FILE: ./private-key.pem

      - name: Copy WAR file to GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ env.PRIVATE_KEY_FILE }}
          script: |
            scp -i "$PRIVATE_KEY_FILE" ${{ needs.build.outputs.war_file }} soulaimeneturki@34.16.175.158:/opt/wildfly/standalone/deployments/
