name: Run gcloud commands

on:
  push:
    branches:
      - main

jobs:
  deploy_to_prod:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
            
        - name: Gcp auth
          uses: 'google-github-actions/auth@v1'
          with: 
            credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}'
          
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 363.0.0'

        - name: Run gcloud commands
          run: |
            gcloud auth list
            gcloud config list
            echo "Hello, GitHub Actions!"
