name: Run gcloud commands

on:
  push:
    branches:
      - main

jobs:
  run_commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }} > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project your-gcp-project-id
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1

      - name: Run gcloud commands
        run: |
          # Example: List GCP buckets and echo some data
          gcloud auth list
          gcloud config list
          echo "Hello, GitHub Actions!"
